export const ActionTypes = {
    FETCH_ITEMS: "FETCH_ITEMS",
    FETCH_ITEM: "FETCH_ITEM",
    UPDATE_SELECTED_ITEM: "UPDATE_SELECTED_ITEM",
    DELETE_SELECTED_ITEM: "REMOVE_SELECTED_ITEM",


    SEARCH_POSTAL: "SEARCH_POSTAL",
    FETCH_UNIVERSITY: 'FETCH_UNIVERSITY',
}