export const ActionTypes = {
    FETCH_ITEMS: "FETCH_ITEMS",
    GET_ITEMS: "GET_ITEMS",
    SET_ITEMS: "SET_ITEMS",
    SELECTED_ITEM: "SELECTED_ITEM",
    DELETE_SELECTED_ITEM: "REMOVE_SELECTED_ITEM",
    UPDATE_SELECTED_ITEM: "UPDATE_SELECTED_ITEM",
}